#!/bin/sh
(cd browserdetect; ./build.sh $*)
(cd dynamictable; ./build.sh $*)
(cd gears; ./build.sh $*)
(cd gridtest; ./build.sh $*)
(cd helloworld; ./build.sh $*)
(cd jsonrpc; ./build.sh $*)
(cd kitchensink; ./build.sh $*)
(cd libtest; ./build.sh $*)
(cd mail; ./build.sh $*)
(cd onclicktest; ./build.sh $*)
(cd addonsgallery; ./build.sh $*)
(cd controls; ./build.sh $*)
(cd formpanel; ./build.sh $*)
(cd getattr; ./build.sh $*)
(cd gridedit; ./build.sh $*)
(cd infohierarchy; ./build.sh $*)
(cd jsobject; ./build.sh $*)
(cd showcase; python compile.py $*)
(cd slideshow; ./build.sh $*)
(cd splitpanel; ./build.sh $*)
(cd tabpanelwidget; ./build.sh $*)
(cd toggle; ./build.sh $*)
(cd widgets; ./build.sh $*)
(cd ajaxlibtest; ./build.sh $*)
(cd xmldoc; ./build.sh $*)
